In [1]:
import numpy as np
import matplotlib.pyplot as plt

from util.zonotope import Zonotope
from util.constrained_zonotope import ConstrainedZonotope

In [2]:
z1 = Zonotope(np.zeros((2,1)),np.eye(2))
z2 = Zonotope(np.ones((2,1)),np.eye(2))

In [3]:
z3 = np.eye(2) * z1

In [4]:
print(z3)

center:
 [[0.]
 [0.]] 
 generators:
 [[1. 0.]
 [0. 1.]]


In [5]:
print(z1 + z2)

center:
 [[1.]
 [1.]] 
 generators:
 [[1. 0. 1. 0.]
 [0. 1. 0. 1.]]


In [5]:
z3.vertices()

array([[-1.,  1.,  1., -1.],
       [-1., -1.,  1.,  1.]])

In [21]:
G = np.random.rand(3,4) - 0.5
Gnorm = G
Gnorm[:,G[1,:]<0] = Gnorm[:,G[1,:]<0] * -1

In [28]:
angles = np.arctan(G[0,:],G[1,:])
np.argsort(angles)

array([1, 2, 0, 3], dtype=int64)